services:
  ackermann-steering:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority