ekf_filter_node:
  ros__parameters:
    frequency: 30.0 # Hz
    sensor_timeout: 0.1

    two_d_mode: true         # For ground vehicles
    publish_tf: true
    map_frame: map           # Frame published by SLAM
    odom_frame: odom         # Frame for filtered odometry
    base_link_frame: base_footprint  # The main robot frame
    world_frame: odom        # What frame the output pose is relative to

    # Odometry (wheel)
    odometry0: /odom
    odometry0_config: [true, true, false,   # X, Y, Z
                       false, false, true,  # Roll, Pitch, Yaw (yaw from odom!)
                       true, false, false,  # vx, vy, vz
                       false, false, true]  # vroll, vpitch, vyaw
    odometry0_differential: false
    odometry0_relative: false

    # IMU
    imu0: /imu/data
    imu0_config: [false, false, false,      # X, Y, Z (IMU pos not used)
                  true, true, true,         # Roll, Pitch, Yaw (only yaw matters in 2d mode)
                  false, false, false,      # vx, vy, vz
                  true, true, true]         # vroll, vpitch, vyaw (angular velocity!)
    imu0_differential: false
    imu0_relative: false
    imu0_remove_gravitational_acceleration: true

    print_diagnostics: true