controller_manager:
  ros__parameters:
    update_rate: 60  # Hz
  
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    rear_left_wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    rear_right_wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    front_left_steering_position_controller:
      type: position_controllers/JointGroupPositionController

    front_right_steering_position_controller:
      type: position_controllers/JointGroupPositionController

joint_state_broadcaster:
  ros__parameters:
    joints:
      - rear_left_wheel_joint
      - rear_right_wheel_joint
      - front_left_steering_joint
      - front_right_steering_joint

rear_left_wheel_velocity_controller:
  ros__parameters:
    joints:
      - rear_left_wheel_joint
    state_publish_rate: 50
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity
    pid: {p: 1.0, i: 0.0, d: 0.0, i_clamp: 0.0}

rear_right_wheel_velocity_controller:
  ros__parameters:
    joints:
      - rear_right_wheel_joint
    state_publish_rate: 50
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity
    pid: {p: 1.0, i: 0.0, d: 0.0, i_clamp: 0.0}

front_left_steering_position_controller:
  ros__parameters:
    joints:
      - front_left_steering_joint
    state_publish_rate: 50
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
    pid: {p: 1.0, i: 0.0, d: 0.0, i_clamp: 0.0}

front_right_steering_position_controller:
  ros__parameters:
    joints:
      - front_right_steering_joint
    state_publish_rate: 50
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
    pid: {p: 1.0, i: 0.0, d: 0.0, i_clamp: 0.0}
