  <!-- Base footprint is a virtual frame at the ground directly beneath the robot's center -->
  <!-- <link name="base_footprint"/> -->


  <!-- Connect base_footprint to base_link with fixed joint but no physical constraints -->
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <!-- Position base_link at the 3D center of the robot, above the footprint -->
    <origin xyz="0 0 ${ground_clearance + chassis_height/2}" rpy="0 0 0"/>
  </joint>