<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="ackermann_robot">
  <!--**********************-->
  <!-- Define Macros/Properties -->
  <!--**********************-->
  <xacro:property name="chassis_length" value="0.6"/>
  <xacro:property name="chassis_width"  value="0.4"/>
  <xacro:property name="chassis_height" value="0.1"/>

  <!-- Wheel dimensions -->
  <xacro:property name="wheel_radius"  value="0.05"/>
  <xacro:property name="wheel_width"   value="0.03"/>

  <!-- Axle distances -->
  <xacro:property name="wheelbase"      value="0.4"/>  <!-- distance between front and rear axles -->
  <xacro:property name="track_width"    value="0.3"/>  <!-- distance between left and right wheels -->

  <!--**********************-->
  <!-- Inertial/Visual/Collision Macros -->
  <!--**********************-->
  <xacro:macro name="chassis_link" params="prefix">
    <link name="${prefix}_chassis">
      <visual>
        <geometry>
          <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
        <material name="Blue">
          <color rgba="0 0.2 0.8 1.0"/>
        </material>
        <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
      </visual>
      <collision>
        <geometry>
          <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
        <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="5.0"/>
        <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
      </inertial>
    </link>
  </xacro:macro>

  <xacro:macro name="wheel_link" params="name suffix pos_x pos_y pos_z">
    <link name="${name}">
      <visual>
        <!-- Rotate cylinder so its axis aligns with joint axis -->
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <material name="Black">
          <color rgba="0 0 0 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.5"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.0005"/>
      </inertial>
    </link>

    <!-- Joint connecting wheel to chassis or steering link -->
    <joint name="${name}_joint" type="continuous">
      <parent link="${suffix}"/>
      <child  link="${name}"/>
      <origin xyz="${pos_x} ${pos_y} ${pos_z}" rpy="0 0 0"/>
      <axis   xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!--**********************-->
  <!-- Chassis -->
  <!--**********************-->
  <xacro:chassis_link prefix="base"/>

  <!--**********************-->
  <!-- Steering Links -->
  <!--**********************-->
  <link name="front_left_steering_link">
    <visual>
      <geometry>
        <box size="0.02 0.02 0.02"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.02 0.02 0.02"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>
  <joint name="front_left_steering_joint" type="revolute">
    <parent link="base_chassis"/>
    <child  link="front_left_steering_link"/>
    <origin xyz="${wheelbase/2} ${track_width/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis  xyz="0 0 1"/>
    <limit lower="-0.785" upper="0.785" effort="5.0" velocity="5.0"/>
  </joint>

  <link name="front_right_steering_link">
    <visual>
      <geometry>
        <box size="0.02 0.02 0.02"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.02 0.02 0.02"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>
  <joint name="front_right_steering_joint" type="revolute">
    <parent link="base_chassis"/>
    <child  link="front_right_steering_link"/>
    <origin xyz="${wheelbase/2} -${track_width/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis  xyz="0 0 1"/>
    <limit lower="-0.785" upper="0.785" effort="5.0" velocity="5.0"/>
  </joint>

  <!--**********************-->
  <!-- Rear Wheels (driven) -->
  <!--**********************-->
  <xacro:wheel_link
    name="rear_left_wheel"
    suffix="base_chassis"
    pos_x="${-wheelbase/2}"
    pos_y="${track_width/2}"
    pos_z="${wheel_radius}"
  />
  <xacro:wheel_link
    name="rear_right_wheel"
    suffix="base_chassis"
    pos_x="${-wheelbase/2}"
    pos_y="${-track_width/2}"
    pos_z="${wheel_radius}"
  />

  <!--**********************-->
  <!-- Front Wheels (mounted) -->
  <!--**********************-->
  <xacro:wheel_link name="front_left_wheel" suffix="front_left_steering_link" pos_x="0" pos_y="0" pos_z="0"/>
  <xacro:wheel_link name="front_right_wheel" suffix="front_right_steering_link" pos_x="0" pos_y="0" pos_z="0"/>

  <!--**********************-->
  <!-- ros2_control Transmissions -->
  <!--**********************-->
  <ros2_control name="Ackermann" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>
    <joint name="rear_left_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface   name="velocity"/>
    </joint>
    <joint name="rear_right_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface   name="velocity"/>
    </joint>
    <joint name="front_left_steering_joint">
      <command_interface name="position"/>
      <state_interface   name="position"/>
    </joint>
    <joint name="front_right_steering_joint">
      <command_interface name="position"/>
      <state_interface   name="position"/>
    </joint>
  </ros2_control>

  <gazebo>
    <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
      <parameters>$(find ackermann_robot_description)/config/ros2_control.yaml</parameters>
    </plugin>
  </gazebo>


</robot>

